name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.BOT_TOKEN }}
        issue-message: 'Thank you for raising a potential issue!'
        pr-message: 'Thank you for your contribution and welcome aboard! Someone is soon going to respond to your pull request!'
